Add configuration to enable ordered list
toshimaru/jekyll-toc pull request #117
Opened 2020-06-26 03:45 UTC by zsyed91

## Overview

By default `jekyll-toc` generates the HTML using unordered lists. If users desire ordered lists for their table of contents they cannot do so easily. With the changes below, the default behavior of using unordered lists will remain. However a new configuration option will toggle between `<ul></ol>` and `<ol></ol>` tags accordingly.

With the changes, users can add the existing custom classes to the top level heading and sub-headings separately. That way they can style the top heading and sub-headings separately. In this pass, I did not add the functionality to style multiple nested sub-headings but rather just all sub-headings using the existing configuration. If we feel that this would be useful, we can extend the current logic in the PR to inject classes similar to the list items so end users can style each sub-heading separately. This might be overkill so for simplicity, I have left it to just top level heading and sub-headings.

## Changes in PR

* Created new configuration option to enable ordered list through use_ordered_list input
* Default behaviour is false so users will continue to have ul tags
* Using existing class configuration, user can change styling on top ol tag and sub listing ol tags separately
* No ability to update styling on sub-nested ol tags separately but code is open to this change
* Added tests for new logic
* Update README with example of usage and render

2020-06-26 05:05 UTC, zsyed91 commented
I totally missed that another user opened this exact issue https://github.com/toshimaru/jekyll-toc/issues/71. Hope that this PR will be considered! Also I am not sure why the builds above are not running?

2020-07-13 02:34 UTC, zsyed91 commented
@toshimaru friendly ping

2020-08-31 00:54 UTC, toshimaru commented
@zsyed91 Sorry, I totally missed your ping. 
I'm gonna review this in this week for sure.  👍

2020-08-31 00:55 UTC, toshimaru commented
I'd say code base is a bit old? (That's why the CI doesn't run, I guress)

2020-09-05 06:40 UTC, toshimaru requested changes
@zsyed91 I've reviewed! 👍

2020-09-05 06:40 UTC, toshimaru commented on lib/table_of_contents/configuration.rb
> +        'use_ordered_list' => false
I prefer just using `ordered_list` (boolean).

```suggestion
        'ordered_list' => false
```

2020-09-05 06:40 UTC, toshimaru commented on test/parser/test_ordered_list.rb
> +end
Add newline at end of file :)

2020-09-05 06:40 UTC, toshimaru commented on lib/table_of_contents/parser.rb
> +        use_ordered_list? ? ORDERED_LIST_HTML_TAG : UNORDERED_LIST_HTML_TAG
Please Memoize the result.

Also, I feel using constants and separating method is a bit redundant.
I'd say the following code is enough.

```suggestion
        @list_tag ||= @configuration.use_ordered_list? ? 'ol' : 'ul'
```

2020-10-12 15:17 UTC, toshimaru commented
Seems no response for my review, but I'm gonna take this PR.
Thanks @zsyed91

2020-10-12 15:17 UTC, merged

2020-10-12 15:46 UTC, zsyed91 commented
Thanks, I too missed this ping! Relocating but that's done. Thanks for
merging this change. Let me know if there are any follow ups needed.

On Mon, Oct 12, 2020, 10:18 AM Toshimaru <notifications@github.com> wrote:

> Merged #117 <https://github.com/toshimaru/jekyll-toc/pull/117> into
> master.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/toshimaru/jekyll-toc/pull/117#event-3867130487>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB2R3DCS7NNSAT2JDSJOZELSKMM3DANCNFSM4OI6QMNQ>
> .
>